version: '3'

services:
  python_django:
    container_name: python_django
    build:
      context: .
      dockerfile: python-django/Dockerfile
      args:
        PYTHON_BASE: slim
        PYTHON_VERSION: "3.10"
    image: python-django
    restart: always
